version: "3.8"

services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

  balanced-general-writer:
    container_name: balanced-general-writer
    command: /root/conf/
    build:
      context: ./orthanc/writer
      dockerfile: ./Dockerfile
      args:
        - DICOM_AET=CCR
        - ORTHANC_ADMIN=$ORTHANC_ADMIN
        - ORTHANC_ADMIN_PASSWORD=$ORTHANC_ADMIN_PASSWORD
        - ORTHANC_USER=$ORTHANC_USER
        - ORTHANC_USER_PASSWORD=$ORTHANC_USER_PASSWORD
    ports:
      - 4242:4242
    restart: unless-stopped
    depends_on:
      - balanced-reader-db
    extra_hosts:
      - "host.docker.internal:host-gateway"

  reader-1:
    container_name: reader-1
    command: /root/conf/
    build:
      context: ./orthanc/reader
      dockerfile: ./Dockerfile
      args:
        - ORTHANC_USER=$ORTHANC_USER
        - ORTHANC_USER_PASSWORD=$ORTHANC_USER_PASSWORD
    restart: unless-stopped
    depends_on:
      - balanced-reader-db
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  reader-2:
    container_name: reader-2
    command: /root/conf/
    build:
      context: ./orthanc/reader
      dockerfile: ./Dockerfile
      args:
        - ORTHANC_USER=$ORTHANC_USER
        - ORTHANC_USER_PASSWORD=$ORTHANC_USER_PASSWORD
    restart: unless-stopped
    depends_on:
      - balanced-reader-db
    extra_hosts:
      - "host.docker.internal:host-gateway"

  balanced-reader-db:
    container_name: balanced-reader-db
    image: mysql:5.7
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password", "--log-bin-trust-function-creators=1"]
    environment:
      MYSQL_DATABASE: 'otc'
      MYSQL_USER: 'otc'
      MYSQL_PASSWORD: 'otc'
      MYSQL_ROOT_PASSWORD: 'otc'
      MYSQL_ROOT_HOST: '%'
    volumes:
      - balanced-index:/var/lib/mysql:Z
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  balanced-storage:
  balanced-index: